name: DropRateController
version: '1.0.0'
main: com.hinaplugin.dropRateController.DropRateController
api-version: '1.21'
authors: [ hina2113 ]
description: アイテムドロップ率を設定する

commands:
  controller:
    permission: controller.commands

permissions:
  controller.admin:
    children:
      - controller.commands
      - controller.commands.get
      - controller.commands.set
      - controller.commands.reload
      - controller.bypass
    default: op